apiVersion: apps/v1
kind: Deployment
metadata:
    annotations: {}
    labels:
        app: app-02
        app-id: a342eda9-d778-456a-b880-7b54c36d3b96
        cluster-agent-id: 359dcd16-4ecd-422f-9710-f748c9700565
        cluster-agent-name: sandaruwan-kind-agent
        environment-id: c79a17b2-15e0-406f-9a8d-94fc8913f323
        environment-name: uat
        metadata-1: YUBhLmE
        organization-id: 7b000cea-2f5e-4479-879a-771a5337d1c9
        product: app-director
        project-id: 9df2c843-053d-42ee-9ec0-81f6e3829571
    name: appdir-359dcd16-app-02-deployment-uat
    namespace: test-hpa
spec:
    replicas: 1
    revisionHistoryLimit: 1
    selector:
        matchLabels:
            app-id: a342eda9-d778-456a-b880-7b54c36d3b96
            cluster-agent-id: 359dcd16-4ecd-422f-9710-f748c9700565
            environment-id: c79a17b2-15e0-406f-9a8d-94fc8913f323
            environment-name: uat
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            annotations: {}
            labels:
                app: app-02
                app-id: a342eda9-d778-456a-b880-7b54c36d3b96
                cluster-agent-id: 359dcd16-4ecd-422f-9710-f748c9700565
                cluster-agent-name: sandaruwan-kind-agent
                environment-id: c79a17b2-15e0-406f-9a8d-94fc8913f323
                environment-name: uat
                metadata-1: YUBhLmE
                organization-id: 7b000cea-2f5e-4479-879a-771a5337d1c9
                product: app-director
                project-id: 9df2c843-053d-42ee-9ec0-81f6e3829571
        spec:
            containers:
                - envFrom: []
                  image: docker.io/sandaruwan1randoli/spring-app:dev
                  imagePullPolicy: Always
                  name: appdir-359dcd16-app-02
                  ports:
                    - containerPort: 8080
                      protocol: TCP
                  resources:
                    limits:
                        cpu: 100m
                        memory: 256Mi
                    requests:
                        cpu: 100m
                        memory: 256Mi
                  securityContext:
                    privileged: false
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts: []
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            serviceAccountName: app-02-sa-uat
            terminationGracePeriodSeconds: 30
            volumes: []
status: {}
