apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: appdir-c04b948b-hpa-gitops-github-deployment-dev-hpa-controller
    namespace: hpa-test-sandaruwan
spec:
    maxReplicas: 4
    metrics:
        - resource:
            name: memory
            target:
                averageUtilization: 60
                type: Utilization
          type: Resource
    minReplicas: 2
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: appdir-c04b948b-hpa-gitops-github-deployment-dev
