apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: appdir-eec05f81-spring-app-03-deployment-open-shift-hpa-controller
    namespace: app-namespace
spec:
    maxReplicas: 4
    metrics:
        - resource:
            name: cpu
            target:
                averageUtilization: 60
                type: Utilization
          type: Resource
        - resource:
            name: memory
            target:
                averageValue: 400Mi
                type: AverageValue
          type: Resource
    minReplicas: 2
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: appdir-eec05f81-spring-app-03-deployment-open-shift
