apiVersion: v1
kind: Service
metadata:
    annotations: {}
    labels:
        app: spring-app-03
        app-id: 9046e824-794f-467b-be48-a366694ffc54
        cluster-agent-id: 359dcd16-4ecd-422f-9710-f748c9700565
        cluster-agent-name: sandaruwan-kind-agent
        environment-id: 4d197f83-65ca-4ece-b053-76176b333246
        environment-name: uat
        metadata-1: YUBhLmE
        organization-id: 7b000cea-2f5e-4479-879a-771a5337d1c9
        product: app-director
        project-id: 83b8c608-2a48-4703-981f-ed3ee4879a6a
    name: spring-app-03-uat-service0
    namespace: test-hpa
spec:
    ports:
        - name: spring-app-03-uat-service0-1
          port: 9000
          protocol: TCP
          targetPort: 8080
    selector:
        app-id: 9046e824-794f-467b-be48-a366694ffc54
        cluster-agent-id: 359dcd16-4ecd-422f-9710-f748c9700565
        environment-id: 4d197f83-65ca-4ece-b053-76176b333246
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
    annotations: {}
    labels:
        app: spring-app-03
        app-id: 9046e824-794f-467b-be48-a366694ffc54
        cluster-agent-id: 359dcd16-4ecd-422f-9710-f748c9700565
        cluster-agent-name: sandaruwan-kind-agent
        environment-id: 4d197f83-65ca-4ece-b053-76176b333246
        environment-name: uat
        metadata-1: YUBhLmE
        organization-id: 7b000cea-2f5e-4479-879a-771a5337d1c9
        product: app-director
        project-id: 83b8c608-2a48-4703-981f-ed3ee4879a6a
    name: spring-app-03-uat-service1
    namespace: test-hpa
spec:
    ports:
        - name: spring-app-03-uat-service1-1
          port: 9001
          protocol: TCP
          targetPort: 8080
    selector:
        app-id: 9046e824-794f-467b-be48-a366694ffc54
        cluster-agent-id: 359dcd16-4ecd-422f-9710-f748c9700565
        environment-id: 4d197f83-65ca-4ece-b053-76176b333246
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}
