apiVersion: v1
kind: Service
metadata:
    annotations: {}
    labels:
        app: spring-app-03
        app-id: 02945efb-c860-47bc-af81-83bf6a363bec
        cluster-agent-id: 359dcd16-4ecd-422f-9710-f748c9700565
        cluster-agent-name: sandaruwan-kind-agent
        environment-id: bacc0fca-fcae-4290-92d7-a7badccba4aa
        environment-name: uat
        metadata-1: c2FuZGFydXdhbi5sYWtzaGl0aGFAcmFuZG9saS5jYQ
        organization-id: 7b000cea-2f5e-4479-879a-771a5337d1c9
        product: app-director
        project-id: 83b8c608-2a48-4703-981f-ed3ee4879a6a
    name: spring-app-03-uat-service0
    namespace: test-hpa
spec:
    ports:
        - name: spring-app-03-uat-service0-1
          port: 9000
          protocol: TCP
          targetPort: 8080
    selector:
        app-id: 02945efb-c860-47bc-af81-83bf6a363bec
        cluster-agent-id: 359dcd16-4ecd-422f-9710-f748c9700565
        environment-id: bacc0fca-fcae-4290-92d7-a7badccba4aa
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
    annotations: {}
    labels:
        app: spring-app-03
        app-id: 02945efb-c860-47bc-af81-83bf6a363bec
        cluster-agent-id: 359dcd16-4ecd-422f-9710-f748c9700565
        cluster-agent-name: sandaruwan-kind-agent
        environment-id: bacc0fca-fcae-4290-92d7-a7badccba4aa
        environment-name: uat
        metadata-1: c2FuZGFydXdhbi5sYWtzaGl0aGFAcmFuZG9saS5jYQ
        organization-id: 7b000cea-2f5e-4479-879a-771a5337d1c9
        product: app-director
        project-id: 83b8c608-2a48-4703-981f-ed3ee4879a6a
    name: spring-app-03-uat-service1
    namespace: test-hpa
spec:
    ports:
        - name: spring-app-03-uat-service1-1
          port: 9001
          protocol: TCP
          targetPort: 8080
    selector:
        app-id: 02945efb-c860-47bc-af81-83bf6a363bec
        cluster-agent-id: 359dcd16-4ecd-422f-9710-f748c9700565
        environment-id: bacc0fca-fcae-4290-92d7-a7badccba4aa
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}
